3 us 25 f2 forgot password
Eco-Gest/Frontend-Flutter pull request #20
Opened 2024-04-13 13:43 UTC by LaitAh

2024-04-16 08:35 UTC, AugustinSeguin approved these changes

2024-04-18 08:05 UTC, eleonoreeuzenes requested changes
Ajouter des espaces

2024-05-12 22:14 UTC, LaitAh commented
Aperçu des modifications : 
![Capture d’écran 2024-04-22 215724](https://github.com/Eco-Gest/Frontend-Flutter/assets/88582838/dc6e0167-7cd7-4df3-8b13-e4e4cac2ff2d)
![Capture d’écran 2024-04-22 215534](https://github.com/Eco-Gest/Frontend-Flutter/assets/88582838/4a99677b-5331-45e6-875c-b86c8ea0ed49)

2024-05-13 12:39 UTC, eleonoreeuzenes approved these changes

2024-05-13 12:39 UTC, merged