show post participants
Eco-Gest/Frontend-Flutter pull request #31
Opened 2024-05-16 16:31 UTC by AugustinSeguin

2024-05-20 16:27 UTC, eleonoreeuzenes requested changes

2024-05-20 16:27 UTC, eleonoreeuzenes commented on lib/widgets/post/post_content_infos.dart
> +            ] else ...[
le badge défi n'apparait plus , ni ce qu'il se passe dans ce else 
<img width="329" alt="image" src="https://github.com/Eco-Gest/Frontend-Flutter/assets/101570309/13becbc4-d52a-4d94-a3fc-007f7a9abd9e">

2024-05-21 11:31 UTC, eleonoreeuzenes commented on lib/widgets/post/post_content_infos.dart
> +            ] else ...[
@AugustinSeguin enfaite il manque le cas où l'utilisateur n'a pas de photo de profil

2024-05-22 09:59 UTC, AugustinSeguin commented on lib/widgets/post/post_content_infos.dart
> +            ] else ...[
@eleonoreeuzenes la condition est là:
   if (userPostParticipation.user?.id != post?.authorId &&
                          userPostParticipation.user?.image != null) ...[
ligne 147 - 148

2024-05-22 10:06 UTC, eleonoreeuzenes commented on lib/widgets/post/post_content_infos.dart
> +            ] else ...[
niveau UX faudrait une condition userPostParticipation.user?.image = null qui montre aussi ceux qui n'ont pas de photos avec l'image par défaut comme sur la vue profil

2024-05-23 08:02 UTC, merged