trim query before searching
Eco-Gest/Frontend-Flutter pull request #59
Opened 2024-06-19 08:05 UTC by eleonoreeuzenes

- retirer les espace de début et fin avant de lancer la requête de recherche
 - mettre bouton recherche iso au reste de l'app

2024-06-19 10:14 UTC, AugustinSeguin requested changes

2024-06-19 10:14 UTC, AugustinSeguin commented on lib/state_management/search/search_cubit.dart
>        emit(SearchStateError(error.toString()));
il faudrait plutôt garder ce message d'erreur :  emit(SearchStateError("Erreur rencontrée pour votre recherche. Veuillez réessayer."));
car c'est lui qui est affiché si on passe de le catch au niveau de lib/widgets/search/search_results_widget.dart

2024-06-19 19:08 UTC, eleonoreeuzenes commented on lib/state_management/search/search_cubit.dart
>        emit(SearchStateError(error.toString()));
done et ajout de marges sur les côtés pour le message d'erreur

2024-06-20 10:17 UTC, AugustinSeguin approved these changes

2024-06-20 10:17 UTC, merged