UI and Bugs on comments
Eco-Gest/Frontend-Flutter pull request #89
Opened 2024-08-20 11:51 UTC by eleonoreeuzenes

### **Description:**

This PR includes several improvements and changes to the comment section. The following modifications were made:

1. **Comment Layout Redesign:**
   - Reorganized the layout of the comments into a three-column structure:
     - **First Column:** Displays the user's avatar aligned at the top.
     - **Second Column:** Contains the username aligned at the top, with the comment text directly beneath it.
     - **Third Column:** Holds the `CommentContentMenu` aligned at the top.
   - Adjusted padding to have less horizontal space than vertical space for a cleaner look.

2. **Clickable Comment Count:**
   - Added functionality to make the number of comments clickable.
   - This link now navigates the user to the comment section, enhancing the user experience by making it easier to jump directly to the comments.

3. **Updated Comment Deletion Access:**
   - Modified the access to deleting a comment in the popup menu.
   - This change ensures that only users with the appropriate permissions (author of said comment) can see and use the delete option, improving the overall security and user access control.

### **Testing:**
- Manually tested the new layout across various screen sizes to ensure responsiveness and proper alignment.
- Verified the clickable link on the number of comments redirects correctly to the comment section.
- Tested the updated deletion access in the popup menu to ensure it is only visible to authorized users.

2024-08-21 13:06 UTC, AugustinSeguin requested changes

2024-08-21 13:06 UTC, AugustinSeguin commented on lib/widgets/post/post_footer/post_footer_infos.dart
> +              GoRouter.of(context).push('/posts/$postId/comments', extra: comments);
Idée d'évolution : pouvoir quand même naviguer jusqu'à la vue commentaire mais s'il n'y en a aucun afficher un message du type "Soyez le premier à commenter" ?

2024-08-26 15:53 UTC, eleonoreeuzenes commented on lib/widgets/comment/comment_content_menu.dart
> +        items.add(const PopupMenuItem<String>(
merci pour ton retour, la feature a été fix dans le dernier commit

2024-08-29 14:43 UTC, AugustinSeguin approved these changes

2024-08-29 14:44 UTC, merged